import type { CrudConfig } from "@/components/admin/CrudPage";

export const MODULES: Record<string, CrudConfig> = {
  ai_knowledge: {
    table: "ai_knowledge",
    title: "AI Knowledge",
    description:
      "Official Teach Nation answers used by the AI assistant. Only active entries are used; the assistant never invents information beyond these entries and live database values.",
    branchScoped: false,
    orderBy: "sort_order",
    searchFields: ["title", "answer", "category"],
    fields: [
      {
        name: "category",
        label: "Category",
        type: "select",
        required: true,
        options: ["Overview", "Admissions", "Courses", "Fees", "Batches & timings", "Branches", "Results", "Policies", "General"],
      },
      { name: "title", label: "Question / title", required: true, help: "e.g. What documents are needed for admission?" },
      { name: "answer", label: "Official answer", type: "textarea", required: true, help: "Keep it short, factual and parent friendly." },
      { name: "sort_order", label: "Sort order", type: "number", hideInTable: true },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
  },
  course_offerings: {
    table: "course_offerings",
    title: "Direct Apply course catalogue",
    description: "Classes, streams, courses and Monthly / Quarterly / Annual plan prices shown in the online admission wizard.",
    branchScoped: false,
    orderBy: "class_label",
    searchFields: ["course_name", "class_label", "stream"],
    fields: [
      {
        name: "class_label",
        label: "Class",
        type: "select",
        required: true,
        options: [
          "Class 1", "Class 2", "Class 3", "Class 4", "Class 5", "Class 6",
          "Class 7", "Class 8", "Class 9", "Class 10", "Class 11", "Class 12",
          "Banking Exams", "Competitive Exams", "Crash Course",
        ],
      },
      {
        name: "stream",
        label: "Stream (if applicable)",
        type: "select",
        options: ["Commerce", "Science", "Humanities", "All streams"],
        help: "Leave blank for classes without streams.",
      },
      { name: "course_name", label: "Course name", required: true, help: "e.g. Accountancy, Economics" },
      { name: "description", label: "Description", type: "textarea", hideInTable: true, help: "Short line shown under the course name." },
      { name: "monthly_price", label: "Monthly price (₹) — billed every month", type: "number", required: true },
      { name: "quarterly_price", label: "Quarterly price (₹) — billed every 3 months", type: "number", required: true },
      { name: "annual_price", label: "Annual price (₹) — Best Value, full session", type: "number", required: true },
      { name: "image_url", label: "Image", type: "image" },
      { name: "sort_order", label: "Sort order", type: "number", hideInTable: true },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
  },
  students: {
    table: "students",
    title: "Students",
    description: "Student records, guardians, documents and enrolment status.",
    fields: [
      { name: "full_name", label: "Student name", required: true },
      { name: "admission_no", label: "Admission no" },
      { name: "dob", label: "Date of birth", type: "date", required: true },
      { name: "gender", label: "Gender", type: "select", options: ["male", "female", "other"], required: true },
      { name: "class_name", label: "Class", required: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
      { name: "father_name", label: "Father name", required: true },
      { name: "mother_name", label: "Mother name", hideInTable: true },
      { name: "guardian_mobile", label: "Guardian mobile", type: "tel", required: true },
      { name: "alt_mobile", label: "Alternate mobile", type: "tel", hideInTable: true },
      { name: "email", label: "Email", type: "email", hideInTable: true },
      { name: "address", label: "Address", type: "textarea", required: true, hideInTable: true },
      { name: "blood_group", label: "Blood group", hideInTable: true },
      { name: "pin_code", label: "Check-in PIN", hideInTable: true, help: "4-6 digit PIN used for QR/PIN attendance." },
      { name: "status", label: "Status", type: "select", options: ["active", "inactive", "alumni"] },
      { name: "photo_url", label: "Image", type: "image" },
      { name: "remarks", label: "Remarks", type: "textarea", hideInTable: true },
    ],
  },
  teachers: {
    table: "teachers",
    title: "Teachers & Staff",
    description: "Staff directory with qualification, role and joining details.",
    fields: [
      { name: "full_name", label: "Name", required: true },
      { name: "phone", label: "Phone", type: "tel", required: true },
      { name: "email", label: "Email", type: "email", hideInTable: true },
      { name: "qualification", label: "Qualification", required: true },
      { name: "experience_years", label: "Experience (years)", type: "number" },
      { name: "role", label: "Role", required: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
      { name: "joining_date", label: "Joining date", type: "date", required: true },
      { name: "pin_code", label: "Check-in PIN", hideInTable: true },
      { name: "status", label: "Status", type: "select", options: ["active", "on_leave", "inactive"] },
      { name: "photo_url", label: "Image", type: "image" },
      { name: "remarks", label: "Remarks", type: "textarea", hideInTable: true },
    ],
  },
  inventory: {
    table: "inventory",
    title: "Inventory",
    description: "AC, heaters, toys, furniture, stationery, books and devices.",
    fields: [
      { name: "item_name", label: "Item", required: true },
      { name: "category", label: "Category", type: "select", required: true, options: ["ac", "heater", "toys", "furniture", "stationery", "books", "devices", "other"] },
      { name: "quantity", label: "Quantity", type: "number", required: true },
      { name: "condition", label: "Condition", type: "select", options: ["good", "needs_repair", "damaged"] },
      { name: "purchase_date", label: "Purchase date", type: "date" },
      { name: "vendor", label: "Vendor", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
      { name: "remarks", label: "Remarks", type: "textarea", hideInTable: true },
    ],
  },
  activities: {
    table: "activities",
    title: "Events & Competitions",
    description: "Poster making, Teachers' Day and award ceremony highlights.",
    fields: [
      { name: "title", label: "Event title", required: true },
      { name: "activity_date", label: "Date", type: "date", required: true },
      { name: "class_name", label: "Class" },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
      { name: "media_url", label: "Photo / video", type: "media" },
      { name: "media_type", label: "Media type", type: "select", options: ["image", "video"] },
      { name: "description", label: "Description", type: "textarea", hideInTable: true },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  supplies: {
    table: "supplies",
    title: "Books & Study Material",
    description: "Admission kits, modules, test papers and stationery.",
    fields: [
      { name: "name", label: "Item", required: true },
      { name: "kind", label: "Kind", type: "select", options: ["books", "modules", "stationery"], required: true },
      { name: "phase", label: "Phase", type: "select", options: ["at_admission", "after_admission"], required: true },
      { name: "class_name", label: "Class" },
      { name: "price", label: "Price (INR)", type: "number" },
      { name: "stock", label: "Stock", type: "number" },
      { name: "branch_id", label: "Branch", type: "branch" },
      { name: "image_url", label: "Image", type: "media", hideInTable: true },
      { name: "remarks", label: "Remarks", type: "textarea", hideInTable: true },
    ],
  },
  admissions: {
    table: "admissions",
    title: "Admissions & Fee Slips",
    description: "Admission records with fee slip and receipt details.",
    fields: [
      { name: "receipt_no", label: "Receipt no", required: true },
      { name: "student_name", label: "Student", required: true },
      { name: "class_name", label: "Class", required: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
      { name: "guardian_name", label: "Guardian", required: true },
      { name: "guardian_mobile", label: "Mobile", type: "tel", required: true },
      { name: "admission_date", label: "Admission date", type: "date", required: true },
      { name: "total_fee", label: "Total fee", type: "number", required: true },
      { name: "paid_amount", label: "Paid", type: "number", required: true },
      { name: "payment_mode", label: "Mode", type: "select", options: ["cash", "upi", "card", "bank_transfer", "cheque"] },
      { name: "payment_ref", label: "Payment ref", hideInTable: true },
      { name: "remarks", label: "Remarks", type: "textarea", hideInTable: true },
    ],
  },
  attendance: {
    table: "attendance",
    title: "Attendance",
    description: "Daily batch attendance for students and faculty.",
    fields: [
      { name: "person_name", label: "Name", required: true },
      { name: "person_type", label: "Type", type: "select", options: ["student", "faculty"], required: true },
      { name: "attendance_date", label: "Date", type: "date", required: true },
      { name: "check_in", label: "Check in", help: "Format HH:MM" },
      { name: "check_out", label: "Check out", help: "Format HH:MM" },
      { name: "status", label: "Status", type: "select", options: ["present", "late", "absent", "half_day"], required: true },
      { name: "method", label: "Method", type: "select", options: ["manual", "qr", "pin"] },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
      { name: "notes", label: "Notes", type: "textarea", hideInTable: true },
    ],
  },
  "daily-reports": {
    table: "daily_reports",
    title: "Class Reports",
    description: "Daily topic covered, participation and faculty remarks per student.",
    fields: [
      { name: "student_id", label: "Student", required: true, help: "Student ID (copy from Students list)" },
      { name: "report_date", label: "Date", type: "date", required: true },
      { name: "meals", label: "Topics covered" },
      { name: "nap", label: "Homework given" },
      { name: "mood", label: "Participation", type: "select", options: ["excellent", "good", "average", "poor"] },
      { name: "toilet", label: "Doubts raised", hideInTable: true },
      { name: "learning", label: "Learning outcome", type: "textarea", hideInTable: true },
      { name: "notes", label: "Notes", type: "textarea", hideInTable: true },
      { name: "media_url", label: "Photo / video", type: "media", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
    ],
  },
  events: {
    table: "events",
    title: "Calendar & Events",
    description: "Holidays, birthdays, PTM, celebrations and field trips.",
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "event_type", label: "Type", type: "select", required: true, options: ["holiday", "exam", "ptm", "celebration", "seminar", "crash_course"] },
      { name: "event_date", label: "Date", type: "date", required: true },
      { name: "end_date", label: "End date", type: "date" },
      { name: "branch_id", label: "Branch", type: "branch" },
      { name: "description", label: "Description", type: "textarea", hideInTable: true },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  health: {
    table: "health_records",
    title: "Student Wellbeing",
    description: "Medical notes and emergency contacts for enrolled students.",
    fields: [
      { name: "student_id", label: "Student", required: true, help: "Student ID" },
      { name: "allergies", label: "Allergies", type: "textarea" },
      { name: "medications", label: "Medications", type: "textarea" },
      { name: "immunizations", label: "Immunisations", type: "textarea", hideInTable: true },
      { name: "doctor_name", label: "Doctor", hideInTable: true },
      { name: "doctor_phone", label: "Doctor phone", type: "tel", hideInTable: true },
      { name: "emergency_contact_name", label: "Emergency contact" },
      { name: "emergency_contact_phone", label: "Emergency phone", type: "tel" },
      { name: "notes", label: "Notes", type: "textarea", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
    ],
  },
  incidents: {
    table: "incidents",
    title: "Discipline & Incidents",
    description: "Behaviour, safety and discipline reports with guardian acknowledgement.",
    fields: [
      { name: "student_name", label: "Student", required: true },
      { name: "incident_date", label: "Date", type: "date", required: true },
      { name: "incident_type", label: "Type", type: "select", options: ["injury", "safety", "behaviour", "illness"], required: true },
      { name: "severity", label: "Severity", type: "select", options: ["minor", "moderate", "serious"], required: true },
      { name: "description", label: "What happened", type: "textarea", required: true },
      { name: "action_taken", label: "Action taken", type: "textarea", hideInTable: true },
      { name: "reported_by", label: "Reported by", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
      { name: "student_id", label: "Student ID", hideInTable: true, help: "Link the student so guardians can acknowledge." },
    ],
  },
  meals: {
    table: "meal_menus",
    title: "Assignments",
    description: "Assignment sheets issued per batch with submission tracking.",
    fields: [
      { name: "menu_date", label: "Issued on", type: "date", required: true },
      { name: "meal_type", label: "Subject", type: "select", options: ["accountancy", "business_studies", "economics", "mathematics", "science", "english"], required: true },
      { name: "items", label: "Assignment details", type: "textarea", required: true },
      { name: "nutrition_notes", label: "Reference material", hideInTable: true },
      { name: "diet_restrictions", label: "Submission deadline", hideInTable: true },
      { name: "served", label: "Issued", type: "checkbox" },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
    ],
  },
  curriculum: {
    table: "lesson_plans",
    title: "Courses & Batches",
    description: "Batch-wise lesson plans and weekly teaching schedule.",
    fields: [
      { name: "title", label: "Lesson title", required: true },
      { name: "class_name", label: "Batch / Class", required: true },
      { name: "week_of", label: "Week of", type: "date", required: true },
      { name: "teacher_name", label: "Faculty" },
      { name: "objectives", label: "Objectives", type: "textarea", hideInTable: true },
      { name: "activities", label: "Activities", type: "textarea", hideInTable: true },
      { name: "materials", label: "Materials", type: "textarea", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
    ],
  },
  progress: {
    table: "progress_records",
    title: "Tests & Results",
    description: "Test-wise performance tracking for every student.",
    fields: [
      { name: "student_id", label: "Student", required: true, help: "Student ID" },
      { name: "assessed_on", label: "Assessed on", type: "date", required: true },
      { name: "milestone", label: "Test name", required: true },
      { name: "domain", label: "Subject", type: "select", options: ["accountancy", "business_studies", "economics", "mathematics", "science", "english", "banking_aptitude"], required: true },
      { name: "rating", label: "Grade", type: "select", options: ["needs_work", "good", "excellent"], required: true },
      { name: "remarks", label: "Remarks", type: "textarea", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
    ],
  },
  "staff-leaves": {
    table: "staff_leaves",
    title: "Faculty Leave",
    description: "Leave requests and approvals.",
    fields: [
      { name: "staff_name", label: "Staff", required: true },
      { name: "leave_type", label: "Type", type: "select", options: ["casual", "sick", "earned", "unpaid"], required: true },
      { name: "from_date", label: "From", type: "date", required: true },
      { name: "to_date", label: "To", type: "date", required: true },
      { name: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected"], required: true },
      { name: "reason", label: "Reason", type: "textarea", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
    ],
  },
  "staff-shifts": {
    table: "staff_shifts",
    title: "Shifts & Assignments",
    description: "Daily shift roster and classroom assignments.",
    fields: [
      { name: "staff_name", label: "Staff", required: true },
      { name: "shift_date", label: "Date", type: "date", required: true },
      { name: "start_time", label: "Start", help: "HH:MM" },
      { name: "end_time", label: "End", help: "HH:MM" },
      { name: "assignment", label: "Assignment" },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
    ],
  },
  "staff-training": {
    table: "staff_training",
    title: "Training Records",
    description: "Staff training programmes and certificates.",
    fields: [
      { name: "staff_name", label: "Staff", required: true },
      { name: "program", label: "Programme", required: true },
      { name: "completed_on", label: "Completed on", type: "date" },
      { name: "certificate_url", label: "Certificate", type: "media", hideInTable: true },
      { name: "remarks", label: "Remarks", type: "textarea", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
    ],
  },
  documents: {
    table: "documents",
    title: "Documents & Forms",
    description: "Consent forms, authorisation letters, handbook and policies.",
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "category", label: "Category", type: "select", required: true, options: ["form", "consent", "handbook", "policy", "licence", "other"] },
      { name: "file_url", label: "File", type: "media" },
      { name: "description", label: "Description", type: "textarea", hideInTable: true },
      { name: "is_public", label: "Visible to parents", type: "checkbox" },
      { name: "requires_consent", label: "Needs signature", type: "checkbox" },
      { name: "branch_id", label: "Branch", type: "branch" },
    ],
  },
  gallery: {
    table: "gallery_items",
    title: "Gallery & Portfolio",
    description: "Monthly gallery and student-wise portfolios.",
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "captured_on", label: "Date", type: "date", required: true },
      { name: "media_url", label: "Photo / video", type: "media", required: true },
      { name: "media_type", label: "Media type", type: "select", options: ["image", "video"] },
      { name: "student_id", label: "Student ID", hideInTable: true, help: "Leave blank for the public gallery." },
      { name: "caption", label: "Caption", type: "textarea", hideInTable: true },
      { name: "is_published", label: "Published", type: "checkbox" },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
    ],
  },
  invoices: {
    table: "invoices",
    title: "Invoices & Dues",
    description: "Fee invoices, partial payments and outstanding dues.",
    fields: [
      { name: "invoice_no", label: "Invoice no", required: true },
      { name: "student_name", label: "Student", required: true },
      { name: "issue_date", label: "Issue date", type: "date", required: true },
      { name: "due_date", label: "Due date", type: "date" },
      { name: "total_amount", label: "Total", type: "number", required: true },
      { name: "paid_amount", label: "Paid", type: "number" },
      { name: "status", label: "Status", type: "select", options: ["unpaid", "partial", "paid", "overdue"], required: true },
      { name: "remarks", label: "Remarks", type: "textarea", hideInTable: true },
      { name: "student_id", label: "Student ID", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
    ],
  },
  payments: {
    table: "payments",
    title: "Payments & Receipts",
    description: "Recorded payments with receipt numbers.",
    fields: [
      { name: "receipt_no", label: "Receipt no", required: true },
      { name: "paid_on", label: "Paid on", type: "date", required: true },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "mode", label: "Mode", type: "select", options: ["cash", "upi", "card", "bank_transfer", "cheque", "online"], required: true },
      { name: "reference", label: "Reference", hideInTable: true },
      { name: "invoice_id", label: "Invoice ID", hideInTable: true },
      { name: "remarks", label: "Remarks", type: "textarea", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
    ],
  },
  inquiries: {
    table: "inquiries",
    title: "Waitlist & Inquiries",
    description: "Lead capture, follow-ups and conversion tracking.",
    fields: [
      { name: "child_name", label: "Student name", required: true },
      { name: "parent_name", label: "Parent name", required: true },
      { name: "mobile", label: "Mobile", type: "tel", required: true },
      { name: "email", label: "Email", type: "email", hideInTable: true },
      { name: "child_dob", label: "Date of birth", type: "date", hideInTable: true },
      { name: "class_interest", label: "Interested in" },
      { name: "status", label: "Status", type: "select", options: ["new", "contacted", "visit_scheduled", "waitlisted", "converted", "lost"], required: true },
      { name: "follow_up_on", label: "Follow up on", type: "date" },
      { name: "source", label: "Source", hideInTable: true },
      { name: "notes", label: "Notes", type: "textarea", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch" },
    ],
  },
  transport: {
    table: "transport_routes",
    title: "Transport Routes",
    description: "Routes, vehicles and drivers.",
    fields: [
      { name: "route_name", label: "Route", required: true },
      { name: "driver_name", label: "Driver" },
      { name: "driver_phone", label: "Driver phone", type: "tel" },
      { name: "vehicle_no", label: "Vehicle no" },
      { name: "stops", label: "Stops", type: "textarea", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
    ],
  },
  pickup: {
    table: "pickup_authorizations",
    title: "Pickup Authorisation",
    description: "Who is allowed to collect each student.",
    fields: [
      { name: "student_name", label: "Student", required: true },
      { name: "person_name", label: "Authorised person", required: true },
      { name: "relation", label: "Relation", required: true },
      { name: "mobile", label: "Mobile", type: "tel", required: true },
      { name: "id_proof", label: "ID proof", hideInTable: true },
      { name: "photo_url", label: "Photo", type: "media", hideInTable: true },
      { name: "is_active", label: "Active", type: "checkbox" },
      { name: "student_id", label: "Student ID", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
    ],
  },
  feedback: {
    table: "feedback_tickets",
    title: "Feedback & Helpdesk",
    description: "Parent queries, complaints, suggestions and ratings.",
    fields: [
      { name: "subject", label: "Subject", required: true },
      { name: "name", label: "From" },
      { name: "mobile", label: "Mobile", type: "tel" },
      { name: "category", label: "Category", type: "select", options: ["query", "complaint", "suggestion", "survey"], required: true },
      { name: "message", label: "Message", type: "textarea", required: true },
      { name: "rating", label: "Rating (1-5)", type: "number" },
      { name: "status", label: "Status", type: "select", options: ["open", "in_progress", "resolved", "closed"], required: true },
      { name: "response", label: "Response", type: "textarea", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch" },
    ],
  },
  surveys: {
    table: "surveys",
    title: "Surveys",
    description: "Parent satisfaction surveys and polls.",
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "is_active", label: "Active", type: "checkbox" },
      { name: "branch_id", label: "Branch", type: "branch" },
    ],
  },
  announcements: {
    table: "announcements",
    title: "Announcements",
    description: "Ticker messages shown across the website.",
    branchScoped: true,
    fields: [
      { name: "message", label: "Message", type: "textarea", required: true },
      { name: "starts_on", label: "Starts on", type: "date" },
      { name: "ends_on", label: "Ends on", type: "date" },
      { name: "is_active", label: "Active", type: "checkbox" },
      { name: "branch_id", label: "Branch", type: "branch" },
    ],
  },
  branches: {
    table: "branches",
    title: "Branch Settings",
    description: "Campus details for Teach Nation 1 and Teach Nation 2.",
    branchScoped: false,
    selectColumns: "id, name, code, address, created_at, updated_at",
    mergeRpc: "branch_contacts",
    fields: [
      { name: "name", label: "Branch name", required: true },
      { name: "code", label: "Code", required: true },
      { name: "phone", label: "Phone", type: "tel" },
      { name: "address", label: "Address", type: "textarea" },
    ],
  },
  videos: {
    table: "site_videos",
    title: "Website Videos",
    description: "Videos shown in the public homepage carousel.",
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "video_url", label: "Video link", required: true, help: "YouTube / Vimeo link, or an uploaded video URL." },
      { name: "thumbnail_url", label: "Thumbnail", type: "media", hideInTable: true },
      { name: "description", label: "Description", type: "textarea", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch" },
      { name: "sort_order", label: "Order", type: "number" },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  classes: {
    table: "classes",
    title: "Classes",
    description: "Class levels taught across the institute.",
    branchScoped: false,
    fields: [
      { name: "name", label: "Class name", required: true },
      { name: "level", label: "Level", type: "number", help: "Used for sorting (e.g. 1–12)." },
      { name: "stream", label: "Stream", type: "select", options: ["general", "commerce", "science", "banking"] },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
  },
  subjects: {
    table: "subjects",
    title: "Subjects",
    description: "Subjects mapped to a class.",
    branchScoped: false,
    fields: [
      { name: "name", label: "Subject", required: true },
      { name: "code", label: "Code" },
      { name: "class_id", label: "Class", type: "ref", refTable: "classes" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
  },
  batches: {
    table: "batches",
    title: "Batches",
    description: "Batch timings with branch, class, subject and faculty.",
    fields: [
      { name: "name", label: "Batch name", required: true },
      { name: "branch_id", label: "Branch", type: "branch", required: true },
      { name: "class_id", label: "Class", type: "ref", refTable: "classes" },
      { name: "subject_id", label: "Subject", type: "ref", refTable: "subjects" },
      { name: "teacher_id", label: "Faculty", type: "ref", refTable: "teachers", refLabel: "full_name" },
      { name: "days", label: "Days", help: "e.g. Mon, Wed, Fri" },
      { name: "start_time", label: "Start time", help: "Format HH:MM" },
      { name: "end_time", label: "End time", help: "Format HH:MM" },
      { name: "capacity", label: "Capacity", type: "number", hideInTable: true },
      { name: "is_active", label: "Active", type: "checkbox" },
      { name: "remarks", label: "Remarks", type: "textarea", hideInTable: true },
    ],
  },
  "student-batches": {
    table: "student_batches",
    title: "Batch allotment",
    description: "Assign students to batches.",
    branchScoped: false,
    fields: [
      { name: "student_id", label: "Student", type: "ref", refTable: "students", refLabel: "full_name", required: true },
      { name: "batch_id", label: "Batch", type: "ref", refTable: "batches", required: true },
      { name: "joined_on", label: "Joined on", type: "date" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
  },
  courses: {
    table: "courses",
    title: "Courses",
    description: "Coaching courses with fee, discount, duration and content.",
    fields: [
      { name: "name", label: "Course name", required: true },
      { name: "class_id", label: "Class", type: "ref", refTable: "classes" },
      { name: "subject_id", label: "Subject", type: "ref", refTable: "subjects" },
      { name: "teacher_id", label: "Faculty", type: "ref", refTable: "teachers", refLabel: "full_name" },
      { name: "branch_id", label: "Branch", type: "branch" },
      { name: "batch_id", label: "Batch", type: "ref", refTable: "batches", hideInTable: true },
      { name: "duration", label: "Duration", help: "e.g. 6 months" },
      { name: "fee", label: "Fee (INR)", type: "number", required: true },
      { name: "discount", label: "Discount (INR)", type: "number" },
      { name: "offer_label", label: "Offer label", hideInTable: true },
      { name: "description", label: "Description", type: "textarea", hideInTable: true },
      { name: "content", label: "Course content", type: "textarea", hideInTable: true },
      { name: "image_url", label: "Image", type: "image" },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  enrollments: {
    table: "enrollments",
    title: "Enrollments",
    description: "Course enrollments created online or added offline.",
    fields: [
      { name: "student_id", label: "Student", type: "ref", refTable: "students", refLabel: "full_name" },
      { name: "course_id", label: "Course", type: "ref", refTable: "courses", required: true },
      { name: "batch_id", label: "Batch", type: "ref", refTable: "batches" },
      { name: "branch_id", label: "Branch", type: "branch" },
      { name: "source", label: "Source", type: "select", options: ["online", "offline"] },
      { name: "status", label: "Status", type: "select", options: ["active", "completed", "cancelled"] },
      { name: "amount_payable", label: "Amount payable", type: "number" },
      { name: "enrolled_on", label: "Enrolled on", type: "date" },
      { name: "remarks", label: "Remarks", type: "textarea", hideInTable: true },
    ],
  },
  "fee-plans": {
    table: "fee_plans",
    title: "Fee plans",
    description: "Total fee and discount agreed per student.",
    fields: [
      { name: "student_id", label: "Student", type: "ref", refTable: "students", refLabel: "full_name", required: true },
      { name: "course_id", label: "Course", type: "ref", refTable: "courses" },
      { name: "branch_id", label: "Branch", type: "branch" },
      { name: "total_fee", label: "Total fee", type: "number", required: true },
      { name: "discount", label: "Discount", type: "number" },
      { name: "notes", label: "Notes", type: "textarea", hideInTable: true },
    ],
  },
  "fee-installments": {
    table: "fee_installments",
    title: "Fee installments & dues",
    description: "Installment schedule, due dates and collected amounts.",
    branchScoped: false,
    fields: [
      { name: "student_id", label: "Student", type: "ref", refTable: "students", refLabel: "full_name", required: true },
      { name: "fee_plan_id", label: "Fee plan", type: "ref", refTable: "fee_plans", refLabel: "id", hideInTable: true, required: true },
      { name: "label", label: "Installment" },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "paid_amount", label: "Paid", type: "number" },
      { name: "due_date", label: "Due date", type: "date", required: true },
      { name: "paid_on", label: "Paid on", type: "date" },
      { name: "method", label: "Method", type: "select", options: ["cash", "upi", "card", "bank_transfer", "cheque"] },
      { name: "reference", label: "Txn / ref id", hideInTable: true },
      { name: "status", label: "Status", type: "select", options: ["pending", "partial", "paid", "overdue"] },
    ],
  },
  "teacher-payments": {
    table: "teacher_payments",
    title: "Faculty payments",
    description: "Salary and honorarium payments made to faculty.",
    fields: [
      { name: "teacher_id", label: "Faculty", type: "ref", refTable: "teachers", refLabel: "full_name", required: true },
      { name: "branch_id", label: "Branch", type: "branch" },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "paid_on", label: "Payment date", type: "date", required: true },
      { name: "period", label: "Month / period", help: "e.g. April 2026" },
      { name: "method", label: "Method", type: "select", options: ["cash", "upi", "bank_transfer", "cheque"] },
      { name: "reference", label: "Reference", hideInTable: true },
      { name: "remarks", label: "Remarks", type: "textarea", hideInTable: true },
    ],
  },
  accounts: {
    table: "ledger_entries",
    title: "Income & expenses",
    description: "All institute income and expense transactions.",
    fields: [
      { name: "kind", label: "Type", type: "select", options: ["income", "expense"], required: true },
      { name: "category", label: "Category", required: true, help: "Fees, rent, salary, electricity, marketing…" },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "entry_date", label: "Date", type: "date", required: true },
      { name: "method", label: "Method", type: "select", options: ["cash", "upi", "card", "bank_transfer", "cheque"] },
      { name: "branch_id", label: "Branch", type: "branch" },
      { name: "reference", label: "Reference", hideInTable: true },
      { name: "description", label: "Description", type: "textarea", hideInTable: true },
    ],
  },
  content: {
    table: "content_items",
    title: "Learning content",
    description: "YouTube lectures, PDFs, notes and worksheets by class, subject and chapter.",
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "content_kind", label: "Type", type: "select", options: ["youtube", "pdf", "notes", "worksheet", "question_paper", "answer_key"], required: true },
      { name: "class_id", label: "Class", type: "ref", refTable: "classes" },
      { name: "subject_id", label: "Subject", type: "ref", refTable: "subjects" },
      { name: "chapter", label: "Chapter" },
      { name: "topic", label: "Topic", hideInTable: true },
      { name: "course_id", label: "Course", type: "ref", refTable: "courses", hideInTable: true },
      { name: "batch_id", label: "Batch", type: "ref", refTable: "batches", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch", hideInTable: true },
      { name: "youtube_url", label: "YouTube link", hideInTable: true },
      { name: "file_url", label: "PDF / file", type: "media" },
      { name: "description", label: "Description", type: "textarea", hideInTable: true },
      { name: "sort_order", label: "Order", type: "number", hideInTable: true },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  tests: {
    table: "tests",
    title: "Tests & exams",
    description: "Objective tests with marks, timing and negative marking.",
    fields: [
      { name: "title", label: "Test title", required: true },
      { name: "class_id", label: "Class", type: "ref", refTable: "classes" },
      { name: "subject_id", label: "Subject", type: "ref", refTable: "subjects" },
      { name: "chapter", label: "Chapter" },
      { name: "batch_id", label: "Batch", type: "ref", refTable: "batches", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch", hideInTable: true },
      { name: "total_marks", label: "Total marks", type: "number" },
      { name: "passing_marks", label: "Passing marks", type: "number" },
      { name: "duration_minutes", label: "Time limit (min)", type: "number" },
      { name: "scheduled_for", label: "Scheduled on", type: "date" },
      { name: "negative_marking", label: "Negative marks / question", type: "number", hideInTable: true },
      { name: "instructions", label: "Instructions", type: "textarea", hideInTable: true },
      { name: "is_published", label: "Published", type: "checkbox" },
    ],
  },
  notifications: {
    table: "notifications",
    title: "Notifications",
    description: "Send announcements, fee reminders and updates to students.",
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "body", label: "Message", type: "textarea", required: true },
      { name: "audience", label: "Audience", type: "select", options: ["all", "class", "batch", "branch", "course"], required: true },
      { name: "class_id", label: "Class", type: "ref", refTable: "classes", hideInTable: true },
      { name: "batch_id", label: "Batch", type: "ref", refTable: "batches", hideInTable: true },
      { name: "branch_id", label: "Branch", type: "branch", hideInTable: true },
      { name: "course_id", label: "Course", type: "ref", refTable: "courses", hideInTable: true },
      { name: "category", label: "Category", type: "select", options: ["general", "fee", "material", "test", "timing", "holiday"] },
    ],
  },
};
